from email.message import EmailMessage
import os
import smtplib
from pathlib import Path


ARTIFACT_DIR = Path("/capsulet/artifacts")
DEFAULT_RECIPIENT = "mohripan16@gmail.com"


def env(name: str, default: str = "") -> str:
    value = os.getenv(name)
    return value if value is not None and value != "" else default


def build_message() -> EmailMessage:
    recipient = env("CAPSULET_EMAIL_TO", DEFAULT_RECIPIENT)
    sender = env("SMTP_FROM", env("SMTP_USERNAME", "capsulet@example.local"))
    subject = env("CAPSULET_EMAIL_SUBJECT", "Capsulet scheduled email")
    body = env(
        "CAPSULET_EMAIL_BODY",
        "This email was generated by a Capsulet automation run.",
    )

    message = EmailMessage()
    message["From"] = sender
    message["To"] = recipient
    message["Subject"] = subject
    message.set_content(body)
    return message


def write_summary(message: EmailMessage, status: str) -> None:
    ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)
    summary = ARTIFACT_DIR / "email-summary.txt"
    summary.write_text(
        "\n".join(
            [
                f"status={status}",
                f"to={message['To']}",
                f"from={message['From']}",
                f"subject={message['Subject']}",
            ]
        )
        + "\n",
        encoding="utf-8",
    )


def send_message(message: EmailMessage) -> None:
    host = env("SMTP_HOST")
    username = env("SMTP_USERNAME")
    password = env("SMTP_PASSWORD")
    port = int(env("SMTP_PORT", "587"))
    use_tls = env("SMTP_TLS", "true").lower() in {"1", "true", "yes"}

    if not host:
        raise RuntimeError("SMTP_HOST is required when CAPSULET_EMAIL_DRY_RUN=false")

    with smtplib.SMTP(host, port, timeout=30) as client:
        if use_tls:
            client.starttls()
        if username or password:
            client.login(username, password)
        client.send_message(message)


def main() -> None:
    message = build_message()
    dry_run = env("CAPSULET_EMAIL_DRY_RUN", "true").lower() in {"1", "true", "yes"}

    if dry_run:
        print(
            f"dry run: would send '{message['Subject']}' "
            f"from {message['From']} to {message['To']}"
        )
        write_summary(message, "dry_run")
        return

    send_message(message)
    print(f"sent '{message['Subject']}' to {message['To']}")
    write_summary(message, "sent")


if __name__ == "__main__":
    main()
