{{- $defaultPool := .Values.executionPools.defaultPool -}}
{{- $otherPools := without (keys .Values.executionPools.pools | sortAlpha) $defaultPool -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "capsulet.fullname" . }}-config
  labels:
    {{- include "capsulet.labels" . | nindent 4 }}
data:
  CAPSULET_LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  RUST_LOG: {{ printf "capsulet=%s,%s" .Values.config.logLevel .Values.config.logLevel | quote }}
  CAPSULET_API_ADDR: "0.0.0.0:8080"
  CAPSULET_SEED_EXAMPLES: {{ .Values.config.seedExamples | quote }}
  CAPSULET_EXECUTION_POOLS: {{ concat (list $defaultPool) $otherPools | join "," | quote }}
  CAPSULET_OBJECT_STORAGE_MODE: {{ include "capsulet.objectStorageMode" . | quote }}
  CAPSULET_OBJECT_STORAGE_PATH: {{ .Values.config.objectStorage.path | quote }}
  CAPSULET_OBJECT_STORAGE_BUCKET: {{ include "capsulet.objectStorageBucket" . | quote }}
  CAPSULET_OBJECT_STORAGE_ENDPOINT: {{ include "capsulet.objectStorageEndpoint" . | quote }}
  CAPSULET_OBJECT_STORAGE_REGION: {{ include "capsulet.objectStorageRegion" . | quote }}
  CAPSULET_OBJECT_STORAGE_PATH_STYLE: {{ include "capsulet.objectStoragePathStyle" . | quote }}
  CAPSULET_DASHBOARD_API_URL: {{ default (printf "http://%s-api" (include "capsulet.fullname" .)) .Values.dashboard.apiBaseUrl | quote }}
  CAPSULET_KAFKA_BROKERS: {{ .Values.config.kafka.brokers | quote }}
  execution-pools.yaml: |
    {{- toYaml .Values.executionPools | nindent 4 }}
