{{- if not .Values.executionIsolation.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "capsulet.fullname" . }}-execution
  labels:
    {{- include "capsulet.labels" . | nindent 4 }}
    app.kubernetes.io/component: execution
automountServiceAccountToken: false
{{- end }}
